# coding: utf-8

"""
    Spinnaker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import spinnaker-python-client
from spinnaker-python-client.models.plugin_dependency import PluginDependency  # noqa: E501
from spinnaker-python-client.rest import ApiException


class TestPluginDependency(unittest.TestCase):
    """PluginDependency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPluginDependency(self):
        """Test PluginDependency"""
        # FIXME: construct object with mandatory attributes with example values
        # model = spinnaker-python-client.models.plugin_dependency.PluginDependency()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
