# coding: utf-8

"""
    Spinnaker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bake_controller_api import BakeControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBakeControllerApi(unittest.TestCase):
    """BakeControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.bake_controller_api.BakeControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bake_options_using_get(self):
        """Test case for bake_options_using_get

        Retrieve a list of available bakery base images for a given cloud provider  # noqa: E501
        """
        pass

    def test_bake_options_using_get1(self):
        """Test case for bake_options_using_get1

        Retrieve a list of available bakery base images, grouped by cloud provider  # noqa: E501
        """
        pass

    def test_lookup_logs_using_get(self):
        """Test case for lookup_logs_using_get

        Retrieve the logs for a given bake  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
