# coding: utf-8

"""
    Spinnaker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.pipeline_controller_api import PipelineControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPipelineControllerApi(unittest.TestCase):
    """PipelineControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.pipeline_controller_api.PipelineControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_pipeline_using_put1(self):
        """Test case for cancel_pipeline_using_put1

        Cancel a pipeline execution  # noqa: E501
        """
        pass

    def test_delete_pipeline_using_delete(self):
        """Test case for delete_pipeline_using_delete

        Delete a pipeline definition  # noqa: E501
        """
        pass

    def test_delete_pipeline_using_delete1(self):
        """Test case for delete_pipeline_using_delete1

        Delete a pipeline execution  # noqa: E501
        """
        pass

    def test_evaluate_expression_for_execution_using_delete(self):
        """Test case for evaluate_expression_for_execution_using_delete

        Evaluate a pipeline expression using the provided execution as context  # noqa: E501
        """
        pass

    def test_evaluate_expression_for_execution_using_get(self):
        """Test case for evaluate_expression_for_execution_using_get

        Evaluate a pipeline expression using the provided execution as context  # noqa: E501
        """
        pass

    def test_evaluate_expression_for_execution_using_head(self):
        """Test case for evaluate_expression_for_execution_using_head

        Evaluate a pipeline expression using the provided execution as context  # noqa: E501
        """
        pass

    def test_evaluate_expression_for_execution_using_options(self):
        """Test case for evaluate_expression_for_execution_using_options

        Evaluate a pipeline expression using the provided execution as context  # noqa: E501
        """
        pass

    def test_evaluate_expression_for_execution_using_patch(self):
        """Test case for evaluate_expression_for_execution_using_patch

        Evaluate a pipeline expression using the provided execution as context  # noqa: E501
        """
        pass

    def test_evaluate_expression_for_execution_using_post(self):
        """Test case for evaluate_expression_for_execution_using_post

        Evaluate a pipeline expression using the provided execution as context  # noqa: E501
        """
        pass

    def test_evaluate_expression_for_execution_using_put(self):
        """Test case for evaluate_expression_for_execution_using_put

        Evaluate a pipeline expression using the provided execution as context  # noqa: E501
        """
        pass

    def test_get_pipeline_logs_using_get(self):
        """Test case for get_pipeline_logs_using_get

        Retrieve pipeline execution logs  # noqa: E501
        """
        pass

    def test_get_pipeline_using_get(self):
        """Test case for get_pipeline_using_get

        Retrieve a pipeline execution  # noqa: E501
        """
        pass

    def test_invoke_pipeline_config_using_post1(self):
        """Test case for invoke_pipeline_config_using_post1

        Trigger a pipeline execution  # noqa: E501
        """
        pass

    def test_invoke_pipeline_config_via_echo_using_post(self):
        """Test case for invoke_pipeline_config_via_echo_using_post

        Trigger a pipeline execution  # noqa: E501
        """
        pass

    def test_pause_pipeline_using_put(self):
        """Test case for pause_pipeline_using_put

        Pause a pipeline execution  # noqa: E501
        """
        pass

    def test_rename_pipeline_using_post(self):
        """Test case for rename_pipeline_using_post

        Rename a pipeline definition  # noqa: E501
        """
        pass

    def test_restart_stage_using_put(self):
        """Test case for restart_stage_using_put

        Restart a stage execution  # noqa: E501
        """
        pass

    def test_resume_pipeline_using_put(self):
        """Test case for resume_pipeline_using_put

        Resume a pipeline execution  # noqa: E501
        """
        pass

    def test_save_pipeline_using_post(self):
        """Test case for save_pipeline_using_post

        Save a pipeline definition  # noqa: E501
        """
        pass

    def test_start_using_post(self):
        """Test case for start_using_post

        Initiate a pipeline execution  # noqa: E501
        """
        pass

    def test_update_pipeline_using_put(self):
        """Test case for update_pipeline_using_put

        Update a pipeline definition  # noqa: E501
        """
        pass

    def test_update_stage_using_patch(self):
        """Test case for update_stage_using_patch

        Update a stage execution  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
