# coding: utf-8

"""
    Spinnaker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.credentials_controller_api import CredentialsControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCredentialsControllerApi(unittest.TestCase):
    """CredentialsControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.credentials_controller_api.CredentialsControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account_using_get(self):
        """Test case for get_account_using_get

        Retrieve an account's details  # noqa: E501
        """
        pass

    def test_get_accounts_using_get(self):
        """Test case for get_accounts_using_get

        Retrieve a list of accounts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
