# coding: utf-8

"""
    Spinnaker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.image_controller_api import ImageControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestImageControllerApi(unittest.TestCase):
    """ImageControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.image_controller_api.ImageControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_images_using_get(self):
        """Test case for find_images_using_get

        Retrieve a list of images, filtered by cloud provider, region, and account  # noqa: E501
        """
        pass

    def test_find_tags_using_get(self):
        """Test case for find_tags_using_get

        Find tags  # noqa: E501
        """
        pass

    def test_get_image_details_using_get(self):
        """Test case for get_image_details_using_get

        Get image details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
