# coding: utf-8

"""
    Spinnaker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import spinnaker-python-client
from spinnaker-python-client.api.job_controller_api import JobControllerApi  # noqa: E501
from spinnaker-python-client.rest import ApiException


class TestJobControllerApi(unittest.TestCase):
    """JobControllerApi unit test stubs"""

    def setUp(self):
        self.api = spinnaker-python-client.api.job_controller_api.JobControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_job_using_get(self):
        """Test case for get_job_using_get

        Get job  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
