# coding: utf-8

"""
    Spinnaker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.search_controller_api import SearchControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchControllerApi(unittest.TestCase):
    """SearchControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.search_controller_api.SearchControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_using_get(self):
        """Test case for search_using_get

        Search infrastructure  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
