# coding: utf-8

"""
    Spinnaker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.firewall_controller_api import FirewallControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFirewallControllerApi(unittest.TestCase):
    """FirewallControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.firewall_controller_api.FirewallControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_by_account_and_region_using_get(self):
        """Test case for all_by_account_and_region_using_get

        Retrieve a list of firewalls for a given account and region  # noqa: E501
        """
        pass

    def test_all_by_account_using_get(self):
        """Test case for all_by_account_using_get

        Retrieve a list of firewalls for a given account, grouped by region  # noqa: E501
        """
        pass

    def test_all_using_get1(self):
        """Test case for all_using_get1

        Retrieve a list of firewalls, grouped by account, cloud provider, and region  # noqa: E501
        """
        pass

    def test_get_security_group_using_get(self):
        """Test case for get_security_group_using_get

        Retrieve a firewall's details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
