# coding: utf-8

"""
    Spinnaker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.snapshot_controller_api import SnapshotControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSnapshotControllerApi(unittest.TestCase):
    """SnapshotControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.snapshot_controller_api.SnapshotControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_current_snapshot_using_get(self):
        """Test case for get_current_snapshot_using_get

        Get current snapshot  # noqa: E501
        """
        pass

    def test_get_snapshot_history_using_get(self):
        """Test case for get_snapshot_history_using_get

        Get snapshot history  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
