# coding: utf-8

"""
    Spinnaker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class PipelineConfigControllerApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def convert_pipeline_config_to_pipeline_template_using_get(self, pipeline_config_id, **kwargs):  # noqa: E501
        """Convert a pipeline config to a pipeline template.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.convert_pipeline_config_to_pipeline_template_using_get(pipeline_config_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str pipeline_config_id: pipelineConfigId (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.convert_pipeline_config_to_pipeline_template_using_get_with_http_info(pipeline_config_id, **kwargs)  # noqa: E501
        else:
            (data) = self.convert_pipeline_config_to_pipeline_template_using_get_with_http_info(pipeline_config_id, **kwargs)  # noqa: E501
            return data

    def convert_pipeline_config_to_pipeline_template_using_get_with_http_info(self, pipeline_config_id, **kwargs):  # noqa: E501
        """Convert a pipeline config to a pipeline template.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.convert_pipeline_config_to_pipeline_template_using_get_with_http_info(pipeline_config_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str pipeline_config_id: pipelineConfigId (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['pipeline_config_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method convert_pipeline_config_to_pipeline_template_using_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'pipeline_config_id' is set
        if ('pipeline_config_id' not in params or
                params['pipeline_config_id'] is None):
            raise ValueError("Missing the required parameter `pipeline_config_id` when calling `convert_pipeline_config_to_pipeline_template_using_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'pipeline_config_id' in params:
            path_params['pipelineConfigId'] = params['pipeline_config_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/pipelineConfigs/{pipelineConfigId}/convertToTemplate', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all_pipeline_configs_using_get(self, **kwargs):  # noqa: E501
        """Get all pipeline configs.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_pipeline_configs_using_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[object]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_pipeline_configs_using_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_pipeline_configs_using_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_pipeline_configs_using_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get all pipeline configs.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_pipeline_configs_using_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[object]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_pipeline_configs_using_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/pipelineConfigs', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[object]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_pipeline_config_history_using_get(self, pipeline_config_id, **kwargs):  # noqa: E501
        """Get pipeline config history.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_pipeline_config_history_using_get(pipeline_config_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str pipeline_config_id: pipelineConfigId (required)
        :param int limit: limit
        :return: list[object]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_pipeline_config_history_using_get_with_http_info(pipeline_config_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_pipeline_config_history_using_get_with_http_info(pipeline_config_id, **kwargs)  # noqa: E501
            return data

    def get_pipeline_config_history_using_get_with_http_info(self, pipeline_config_id, **kwargs):  # noqa: E501
        """Get pipeline config history.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_pipeline_config_history_using_get_with_http_info(pipeline_config_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str pipeline_config_id: pipelineConfigId (required)
        :param int limit: limit
        :return: list[object]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['pipeline_config_id', 'limit']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_pipeline_config_history_using_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'pipeline_config_id' is set
        if ('pipeline_config_id' not in params or
                params['pipeline_config_id'] is None):
            raise ValueError("Missing the required parameter `pipeline_config_id` when calling `get_pipeline_config_history_using_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'pipeline_config_id' in params:
            path_params['pipelineConfigId'] = params['pipeline_config_id']  # noqa: E501

        query_params = []
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/pipelineConfigs/{pipelineConfigId}/history', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[object]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
