# coding: utf-8

"""
    Spinnaker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EnvironmentArtifactVeto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'comment': 'str',
        'reference': 'str',
        'target_environment': 'str',
        'version': 'str'
    }

    attribute_map = {
        'comment': 'comment',
        'reference': 'reference',
        'target_environment': 'targetEnvironment',
        'version': 'version'
    }

    def __init__(self, comment=None, reference=None, target_environment=None, version=None):  # noqa: E501
        """EnvironmentArtifactVeto - a model defined in Swagger"""  # noqa: E501

        self._comment = None
        self._reference = None
        self._target_environment = None
        self._version = None
        self.discriminator = None

        if comment is not None:
            self.comment = comment
        if reference is not None:
            self.reference = reference
        if target_environment is not None:
            self.target_environment = target_environment
        if version is not None:
            self.version = version

    @property
    def comment(self):
        """Gets the comment of this EnvironmentArtifactVeto.  # noqa: E501


        :return: The comment of this EnvironmentArtifactVeto.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this EnvironmentArtifactVeto.


        :param comment: The comment of this EnvironmentArtifactVeto.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def reference(self):
        """Gets the reference of this EnvironmentArtifactVeto.  # noqa: E501


        :return: The reference of this EnvironmentArtifactVeto.  # noqa: E501
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference):
        """Sets the reference of this EnvironmentArtifactVeto.


        :param reference: The reference of this EnvironmentArtifactVeto.  # noqa: E501
        :type: str
        """

        self._reference = reference

    @property
    def target_environment(self):
        """Gets the target_environment of this EnvironmentArtifactVeto.  # noqa: E501


        :return: The target_environment of this EnvironmentArtifactVeto.  # noqa: E501
        :rtype: str
        """
        return self._target_environment

    @target_environment.setter
    def target_environment(self, target_environment):
        """Sets the target_environment of this EnvironmentArtifactVeto.


        :param target_environment: The target_environment of this EnvironmentArtifactVeto.  # noqa: E501
        :type: str
        """

        self._target_environment = target_environment

    @property
    def version(self):
        """Gets the version of this EnvironmentArtifactVeto.  # noqa: E501


        :return: The version of this EnvironmentArtifactVeto.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this EnvironmentArtifactVeto.


        :param version: The version of this EnvironmentArtifactVeto.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnvironmentArtifactVeto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnvironmentArtifactVeto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
